### ISSUE TITLE
refactor(dein): mv add/foo.vim to foo/add.vim for each plugin, vim-foo

### ISSUE THREAD

**Issue by kaile256** [kaile256/dotfiles#1]
Currently, I manage config plugins via dein as the following format:

```toml
[[plugins]]
repo = 'foobar/foo'
lazy = 1
hook_add = 'runtime add/foo.vim
hook_source = 'runtime source/foo.vim
hook_post_source = 'runtime post/foo.vim
```

But another format may let me easier to manage like the following format:

```toml
...
hook_add = 'runtime foo/add.vim'
hook_source = 'runtime foo/source.vim'
hook_post_source = 'runtime foo/post.vim'
```

It requires consideration.
